# NumPy



## What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,including mathematical, logical, shape mamipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the *ndarray* object. This encapsulates *n*-dimensional arrarys of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an *ndarray* will create a new array and delete the original.

- The elements in a Numpy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today's scientific/mathematical Python-based software, just knowing how to use Python's built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

In [1]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

NameError: name 'a' is not defined

## [Glossary](https://numpy.org/doc/stable/glossary.html)



###  -1

- **In a dimension entry**, instructs NumPy to choose the length that will keep the total number of array elements the same.

- **In an index** , any negative value denotes indexing from the right.

In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b = a.reshape(4, -1)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
b.shape

(4, 3)

## [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)



## [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html)

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name # 教程运行结果是'int64'

'int32'

In [13]:
a.itemsize # 教程运行结果是8

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [11]:
b =np.array([6, 7, 8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [14]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [16]:
a.dtype # 教程运行结果是dtype('int64')

dtype('int32')