# NumPy



## What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,including mathematical, logical, shape mamipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the *ndarray* object. This encapsulates *n*-dimensional arrarys of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

## [Glossary](https://numpy.org/doc/stable/glossary.html)



###  -1

- **In a dimension entry**, instructs NumPy to choose the length that will keep the total number of array elements the same.

- **In an index** , any negative value denotes indexing from the right.

In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b = a.reshape(4, -1)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
b.shape

(4, 3)

## [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)



## [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html)

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name # 教程运行结果是'int64'

'int32'

In [13]:
a.itemsize # 教程运行结果是8

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [11]:
b =np.array([6, 7, 8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [14]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [16]:
a.dtype # 教程运行结果是dtype('int64')

dtype('int32')