# Sequences in Python

[Sequences in Python with Types and Examples](https://pythongeeks.org/python-sequences-types-examples/)


In [9]:
a = [0, 1, 2, 3, 4]
b = [5, 6, 7, 8, 9]

a + b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [2]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])
a + b

array([ 5,  7,  9, 11, 13])

In [6]:
a - b

array([-5, -5, -5, -5, -5])

In [4]:
a * b

array([ 0,  6, 14, 24, 36])

In [5]:
a / b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [12]:
b ** 2

array([25, 36, 49, 64, 81])