# NumPy



In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name # 教程运行结果是'int64'

'int32'

In [13]:
a.itemsize # 教程运行结果是8

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [11]:
b =np.array([6, 7, 8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [14]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [16]:
a.dtype # 教程运行结果是dtype('int64')

dtype('int32')